adding mongodb storage backend
metal-stack/go-ipam pull request #80
Opened 2022-07-18 15:44 UTC by f00actual

adding mongodb storage backend

closes #79

2022-07-18 16:23 UTC, majst01 commented
Nice so far, please check the output of `golangci-lint run -p bugs -p unused`

2022-07-18 16:24 UTC, majst01 requested changes

2022-07-18 16:24 UTC, majst01 commented on testing_test.go
> +	"os"
please keep stdlibrary imports at the top

2022-07-18 16:47 UTC, majst01 commented
Can you please add some useful entries to the Readme as well, especially the table with the supported mongodb versions and some "normalized" benchmark numbers. According to the ci run the benchmark shows a ~ 2x performance of the postgres version.

2022-07-18 18:16 UTC, f00actual commented
What approach did you take for the op/sec normalization in the README.md? It appears the latest bench results ran on different hardware and they might need updated overall. What do you think?

2022-07-19 05:23 UTC, majst01 commented
> What approach did you take for the op/sec normalization in the README.md? It appears the latest bench results ran on different hardware and they might need updated overall. What do you think?

Like your current layout, but the problem persist, these hardware specs are hard to achieve. And what is actually running in the ci pipeline is not known.

2022-07-19 12:56 UTC, majst01 approved these changes

2022-07-19 12:56 UTC, majst01 commented
I think this is ready for merging

2022-07-20 05:43 UTC, merged